alias as='apt-cache search'
alias cat='batcat'
alias dir='dir --color=auto'
alias dot="$(which git) --git-dir=${HOME}/projects/dotfiles --work-tree=${HOME}"
alias e="${EDITOR}"
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias g="$(which git)"
alias grep='grep --color=auto'
alias i='sudo apt install'
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -l'
alias ls='ls --color=auto --group-directories-first'
alias r='sudo apt remove -y && sudo autoremove -y'
alias u='sudo apt update && sudo upgrade -y'
alias vdir='vdir --color=auto'
